CREATE TABLE IF NOT EXISTS `#__bookstock` (
  `id` INT(11) NOT NULL PRIMARY KEY,
  `qty` INT(11) NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `#__bookstock` (`id`, `qty`) VALUES (1, 0)
  ON DUPLICATE KEY UPDATE qty = qty;
